version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "30433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  dbmate:
    image: amacneil/dbmate
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
    command: "--wait up"
    working_dir: /app
    volumes:
      - ./db:/app/db
    depends_on:
      - db
  backend:
    image: sororiri/memo-backend:test
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    env_file:
      - ./.env.development
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
    volumes:
      - ./public:/app/public
    depends_on:
      - dbmate
