version: '3'
services:
  backend:
    image: sororiri/memo-backend:0.0.21
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./.env.dev
    environment:
      DB_HOST: localhost
      DB_PORT: 30433
      DB_TYPE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
    volumes:
      - ./public:/app/public
