FROM node:20-alpine

WORKDIR /app

COPY package*.json .

RUN yarn install --frozen-lockfile

COPY . .

ENV HASH_ROUNDS=7
ENV JWT_SECRET=leesecret
ENV BACKEND_PORT=3001
ENV BACKEND_URL=localhost

ENV DB_HOST=db
ENV DB_PORT=5432
ENV DB_TYPE=postgres
ENV DB_USERNAME=postgres
ENV DB_PASSWORD=postgres
ENV DB_DATABASE=postgres

EXPOSE 3001

CMD ["yarn", "start"]

