version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "30433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  dbmate:
    image: amacneil/dbmate
    env_file:
      - ./.docker.env.local
    command: "--wait up"
    working_dir: /app
    volumes:
      - ./db:/app/db
    depends_on:
      - db
    extra_hosts:
      host.docker.internal: host-gateway
