CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nickname" varchar(100) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(100) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "role" varchar(10) DEFAULT ''
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "users_id" integer NOT NULL,
  "title" varchar(300) NOT NULL,
  "content" varchar(6000) NOT NULL,
  "cate_id" integer,
  "thumnail_img_url" varchar(1000),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pos" integer,
  "users_id" integer,
  "category_name" varchar(150) NOT NULL,
  "parent_cate_id" integer
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "posts_id" integer,
  "users_id" integer,
  "content" varchar(1000) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "files" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "original_filename" VARCHAR(255) NOT NULL,
  "stored_filename" VARCHAR(255) NOT NULL,
  "file_size" BIGINT NOT NULL,
  "mime_type" VARCHAR(100),
  "upload_date" TIMESTAMP NOT NULL DEFAULT (now()),
  "post_id" INTEGER NOT NULL,
  "user_id" INTEGER,
  "file_path" VARCHAR(1000) NOT NULL,
  "description" TEXT
);

ALTER TABLE "posts" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("cate_id") REFERENCES "categories" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_cate_id") REFERENCES "categories" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("posts_id") REFERENCES "posts" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "files" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "files" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
